dist: xenial

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.4.2

before_install:
  - docker pull trufflesuite/ganache-cli:v6.8.1
  - mkdir -p ./db_ganache
  - docker run -d -p 8545:8545 --name my_ganache -v "$PWD/db_ganache":/app/db_ganache trufflesuite/ganache-cli:v6.8.1 --mnemonic "width whip dream dress captain vessel mix drive oxygen broken soap bone" --db "db_ganache/"


jobs:
  include:
    - stage: "Deploy Contracts"
      language: node_js
      node_js:
        - "lts/dubnium"
      install:
        - cd workspace-blockchain
        - yarn
      script:
        - yarn deploy:ganache:local
    - stage: test
      language: android
      jdk: openjdk8
      android:
        components:
          - build-tools-29.0.2
          - android-29
        licenses:
          - 'android-sdk-preview-license-52d11cd2'
          - 'android-sdk-license-.+'
          - 'google-gdk-license-.+'
      install:
        - cd workspace-android
        - ./gradlew assemble
      script:
        - ./gradlew test --stacktrace
    -
      language: node_js
      node_js: "lts/dubnium"
      install:
        - cd workspace-blockchain
        - yarn
      script:
        - yarn test:ci
        - yarn coverage:ci
        - yarn lint
        - npx codechecks
    -
      language: node_js
      node_js: "lts/dubnium"
      install:
        - cd workspace-webui
        - yarn
      script:
        - yarn lint
