os: linux
dist: xenial
language: node_js
node_js: lts/dubnium

services:
  - docker
  - postgresql

cache:
  yarn: true
  directories:
    - node_modules

env:
  - DOCKER_COMPOSE_VERSION=1.4.2

jobs:
  include:
    - stage: test
      before_install:
        - cd templates/smart-contracts
      install:
        - yarn
      script:
        - yarn test
        - yarn coverage
        - yarn lint
        - npx codechecks
    -
      before_install:
        - docker pull trufflesuite/ganache-cli:v6.9.1
        - mkdir -p ./db_ganache
        - docker run -d -p 8545:8545 --name my_ganache -v "$PWD/db_ganache":/app/db_ganache trufflesuite/ganache-cli:v6.9.1 --mnemonic "width whip dream dress captain vessel mix drive oxygen broken soap bone" --db "db_ganache/"
        - (cd templates/smart-contracts && yarn && yarn deploy:ganache:local)
        - cd templates/react-webui
      install:
        - yarn
      script:
        - netstat -an --tcp --program
        - yarn test
    -
      before_install:
        - cd templates/api
      install:
        - yarn
      before_script:
        - psql -c 'create database starterkitcache;' -U postgres
        - psql -c 'create table setvalue(id int primary key, newvalue integer, tx text unique, sender text);' -U postgres
      script:
        - yarn test
