# This is an example with only required properties:
version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/workspace-webui"
    update_schedule: "daily"
    default_assignees:
      - "obernardovieira"
    ignored_updates:
      - match:
          dependency_name: "jest"
          dependency_name: "typescript"
          dependency_name: "react-scripts"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "all"

  - package_manager: "javascript"
    directory: "/workspace-blockchain"
    update_schedule: "daily"
    default_assignees:
      - "obernardovieira"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "all"
