# This is an example with only required properties:
version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "weekly"
    default_assignees:
      - "obernardovieira"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "all"

  - package_manager: "javascript"
    directory: "/templates/react-webui"
    update_schedule: "weekly"
    default_assignees:
      - "obernardovieira"
    ignored_updates:
      - match:
          dependency_name: "jest"
      - match:
          dependency_name: "ts-jest"
      - match:
          dependency_name: "eslint"
      - match:
          dependency_name: "typescript"
      - match:
          dependency_name: "typedoc"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "all"

  - package_manager: "javascript"
    directory: "/templates/smart-contracts"
    update_schedule: "weekly"
    default_assignees:
      - "obernardovieira"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "all"

  - package_manager: "javascript"
    directory: "/templates/api"
    update_schedule: "weekly"
    default_assignees:
      - "obernardovieira"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "all"
